---
title: "MCMC"
author: "Matej Kalc"
date: '2022-05-18'
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```



## Metropolis-Hastings
```{r}
inverse_sampling <- function(Q, m){
  x_i <- rep(0, m)
  for(i in 1:m) {
    u <- runif()
    x_i(i) <- Q(u)
  }
  return (x_i)
}

rejection_sampling <- function(f,g,M,m) {
  x_i <- rep(0, m)
  for(i in 1:m) {
    
    success <- FALSE
    
    while(!success) {
      y <- sample(g, 1)
      u <- runif()
      
      success <- u <= f(y)/(M * g(y))
    }
    x_i(i) <- y
    
  }
  
  return(x_i)
}



metropolis_hastings <- function(p, k, m, x_0, sampling_method = "inverse") {
  
  x_prev = x_0
  
  x_i = rep(0, m)
  
  for(i in 1:m) {
    if(sampling_method == "inverse") {
      Q = 
      x_c <- inverse_sampling(Q, 1)
    }
    alpha <- min(1, (p(x_c) * k(x_c, x_prev)) / (p(x_prev) * k(x_prev, x_c)))
    
    u <- runif()
    
    if(u <= alpha){
      
      x_i(i) <- x_c
      x_prev <- x_c
    } else {
      x_i(i) <- x_prev
    }
    
  }
  
  return (x_i)
  
  
}
```

